### ISSUE TITLE
Question: What does the parameter version="v2" stand for in the function 

### ISSUE THREAD

**Issue by nba2020** [yogat3ch/AlpacaforR#18]
It's been a while since I've used the API and spotted the version parameter.
What does `version="v2"` stand for in the package functions?

**Comment by yogat3ch** [comment]
Alpaca started with the v1 API, but has since migrated to the v2 API. The argument is there to indicate which API version to use. In just about every situation it's going to be v2, the default.
I'm actually just finishing up an overhaul of the package with a great deal more documentation and *hopefully* more intuitively named functions that match the Endpoint names in the [Alpaca v2 documentation](https://alpaca.markets/docs/api-documentation/api-v2/). It won't be entirely backwards compatible with the current AlpacaforR build, so you may need to update some of your code with search and replace to use the updated package, but I've tried to preserve backwards compatibility with the majority of functions. This argument is a good example of a breaking change with the updates, this argument will change to simply `v` and take an integer as input (since it's fewer keystrokes to type out).
The forthcoming features that I think are most excited are:
- a robust `market_data` function to replace `get_bars` through which both Alpaca or Polygon data can be accessed simply by toggling `v = 1` or `v = 2` respectively keeping all the arguments the same. This function will return **complete** data sets to the extent possible. No more partial data sets based on API limits. Missing data will be marked with `NA` instead of just silently omitted entirely (did you notice that your data had large gaps? :wink:) 
- Full support for [Alpaca Streaming](https://alpaca.markets/docs/api-documentation/api-v2/streaming/) and [Polygon Websocket](https://polygon.io/sockets) services.
- full integration of the Polygon API in a single function

I'll be making some commits for the updates to my [fork of this package](https://github.com/yogat3ch/AlpacaforR) in the next hour. The full functionality will come along after I have a had a chance to debug the functions that can only be debugged during market hours (likely by Tuesday or Wednesday). I'm not sure if/when @jagg19 will be integrating the changes as I've tried to get in touch with him but haven't heard back. Hopefully he will chime in soon.

Hope you're enjoying the package!

**Comment by jagg19** [comment]
Thanks @yogat3ch for responding to this some time ago, it has been a crazy time for me during covid.

>Alpaca started with the v1 API, but has since migrated to the v2 API. The argument is there to indicate which API version to use. In just about every situation it's going to be v2, the default.

This is true and will be addressed in future updates that @yogat3ch has already implemented over on his fork. He has done tremendous work on updating and maintaining AlpacaforR in my absence. Couldn't be grateful enough!
