### ISSUE TITLE
AlpacaforR v1.0.0

### ISSUE THREAD

**Issue by yogat3ch** [yogat3ch/AlpacaforR#26]
Hi @jagg19,
I just finished up writing you an email, and hope to get a response but in case the email attempt is unsuccessful I'm also tagging you here to hopefully get your attention. There are additional details in the email, but here's a basic synopsis of the situation.
I've just pushed some of the final changes to the greatly expanded `AlpacaforR` over at [yogat3ch/AlpacaforR](https://github.com/yogat3ch/AlpacaforR). I'd appreciate your input, if possible, on the CRAN release that I hope to submit by Friday once I add the recently released Alpaca Websockets. Please check your gmail if you get the chance!

**Comment by jagg19** [comment]
Hi @yogat3ch 

I know we emailed earlier but I'd like to keep everything as transparent as possible so I'll also respond on GitHub. I had the chance to go through your changes throughout the day today (all 7 pull requests during the day, and your master tonight) and I am very grateful and amazed at all the work you've done. Tomorrow & the weekend I plan on testing these changes live on my local machine and will be able to give feedback in detail. Please hold off on CRAN publishing until next week.

I created AlpacaforR because not only do I love Alpaca, but I see the huge need for this in the R community. With that said, I would love to continue AlpacaforR with you as a team as I do plan on becoming a lot more active with it again since being a bit distant. I recognize your effort in updating and the work you put into this overhaul, so I'd love for us to continue as co partners with you being primary maintainer. 

I'd love to see AlpacaforR continue to grow as Alpaca does, and raise awareness through various ways. We will chat more in the coming days and relay it here for transparency. Keeping this open until the official CRAN launch. Thanks again for everything!!

**Comment by yogat3ch** [comment]
🤓🎉 Thanks! I'm grateful for the openness to my input! I feel like this package was already more user friendly than the APIs that Alpaca makes for other languages, and with all the updates I think it really has a super compelling use case. We can figure out the details here or over email, whichever you prefer!
