### ISSUE TITLE
Question: How to code a OCO (One-Cancels-Other) order?

### ISSUE THREAD

**Issue by nba2020** [yogat3ch/AlpacaforR#27]
@jagg19 I try to learn and test the OCO sell order type. How may I specify it within the `submit_order()` function?
 Perhaps you could help me with an example for the following desired order parameters:

- take_profit limit_price = 110
- stop_loss stop_price = 98
- stop_loss limit_price = 97.5

**Comment by yogat3ch** [comment]
Hi @nba2020,
AlpacaforR [v1.0.0](https://github.com/yogat3ch/AlpacaforR) has support for bracket orders. You can install it with `remotes::install_github("yogat3ch/AlpacaforR")`. Do also note that v1.0.0 is **not** entirely backwards compatible and will require updating legacy code if you have scripts you tend to re-use. More specifically, while `submit_order` is still a function in v.1.0.0, it's simply a mask for the new `order_submit` which has slightly different syntax for arguments.  All of the functions are well-documented so it should be straightforward as to how to update existing code you may have. 
If you mostly use AlpacaforR at the console in a more interactive, one-off type of way, you can simply update the package and start using the new functionality. 

Once you try it out, will you let me know if you run into any snags or if you're able to get it working so I can determine whether to close the issue or not?

**Comment by aLeXgr2020** [comment]
Thanks for your response @yogat3ch.
May I ask you to clarify the differences between `yogat3ch/AlpacaforR` and `jagg19/AlpacaforR`?
So far I am using `jagg19/AlpacaforR` version. Would OCO orders be feasible without having to switch to `yogat3ch/AlpacaforR`?

**Comment by nba2020** [comment]
Thanks for your response @yogat3ch.

May I kindly ask you to clarify the differences between `yogat3ch/AlpacaforR` and `jagg19/AlpacaforR`?
So far I've developed my trading script by using the `jagg19/AlpacaforR` package version and it works as expected.
Could OCO orders be feasible via `jagg19/AlpacaforR` version without having to switch to `yogat3ch/AlpacaforR` and QA/refactor existing commands across my script?

**Comment by yogat3ch** [comment]
Hi @nba2020,
I'll do my best to answer your questions.
>May I kindly ask you to clarify the differences between yogat3ch/AlpacaforR and jagg19/AlpacaforR? 

Unfortunately the changes are too extensive to detail here (1000+ lines). You could skim through the Readme on `yogat3ch/AlpacaforR` to get a handle on what common functions have changed and how they have changed. If you want a more in depth look, the commits can likely provide that.  

>Could OCO orders be feasible via jagg19/AlpacaforR version without having to switch to yogat3ch/AlpacaforR and QA/refactor existing commands across my script?

You can custom roll your own functionality for OCO using `jagg19/AlpacaforR` by taking apart `submit_orders` and building up the `httr` calls yourself. Depending on your familiarity with `httr` and API calls that might be more effort than just refactoring the code since you won't gain the benefit of all the additional functionality in yogat3ch/AlpacaforR. 

We're working on integrating `yogat3ch/AlpacaforR` and `jagg19/AlpacaforR` once we work out some minor bugs, so the re-factoring is likely going to be necessary at some point in the future anyway. 

Hope that helps
