### ISSUE TITLE
Input on updating to the V2 API & Getting AlpacaforR to CRAN

### ISSUE THREAD

**Issue by yogat3ch** [yogat3ch/AlpacaforR#8]
Hi @jagg19,
As Alpaca continues to roll out updates for solely the V2 API, especially the replace functions that will be super useful for what I'm currently working on, I'm wondering if you would be up for migrating the package to the V2 API? I'm happy to do most of the updates, I'll likely need some help with the syntax to get `httr` to do the `PATCH` request correctly though. See the [post on the Alpaca forums for details](https://forum.alpaca.markets/t/what-s-new-at-alpaca-9-16-2019/280)

Additionally, I was wondering what your thoughts are on getting the package CRAN ready? 
_Note: I've already started this on my local repo and wondering if its worth continuing the effort?_

**Comment by jagg19** [comment]
Hi @yogat3ch 

Im so sorry for letting this hang for so long! I was so busy since getting hired a bit ago, and I was meaning to check the issues for quite some time. I'm definitely up for migrating over to V2, I started some in an update branch a very long time ago, but first I'll check out your updates.

I'd love to get your email so we can chat a little more and have another way to communicate since I can't really use GitHub at work. As for CRAN, I never really gave it any thought tbh. I would need some help since I never prepared a package for CRAN.

**Comment by yogat3ch** [comment]
Yay! Welcome back!
Congratulations on the job! 
I totally get it, my semester is in full swing right now and I have had 0 time to work on this for a couple of weeks. I did make a number of updates before I ran out of time to do so though - some of which I don't think I have made a pull request for. I'll see about doing so around the 2nd week of December when the semester is over.

My email is sholsen at alumni dot emory dot edu - happy to continue the conversation on there as it will likely allow for more ease of communication.

**Comment by jagg19** [comment]
I went ahead and pulled in the minor differences from your forked branch into mine, but I'll keep an eye on for additional pull requests. I've opened another branch called "v2-updates" where all of the V2 updates will live before I merge it into the master, once all is said and done. I hope to make these V2 updates ASAP. 

I'll close this issue once I add the "replace" function to V2. 

I sent an email so let me know if you didn't get it.

**Comment by yogat3ch** [comment]
Ok, I'll take a look and see about synchronizing my repo so we can start on the V2 API.

**Comment by fredwright68** [comment]
Never mind, issue resolved
_Not sure if this belongs in this thread, but for me the current package fails for live=TRUE, but works fine for live=FALSE. Is it currently working for others?_

**Comment by jagg19** [comment]
Hi @fredwright68 , sorry for not responding to this when you replied! 

I see you said it was resolved but did it have something to do with your environment variables for the Key-ID and Secret-Keys?? I tried to set these up in a way where the get_headers function will handle it appropriately since the keys for either paper or live accounts have to have the same naming convention. 

In the V2 update that I am going to push hopefully by the end of this week, will be a little more straight forward. I recommend naming your variables like the below, so you can easily distinguish between your "live account" and "paper account" keys (this is how the V2 get_headers function will read your variables). 

Live Keys:
`'APCA-API-KEY-ID' = Sys.getenv("APCA-LIVE-API-KEY-ID")`  &nbsp;
`'APCA-API-SECRET-KEY' = Sys.getenv("APCA-LIVE-API-SECRET-KEY")`

Paper Keys:           
`'APCA-API-KEY-ID' = Sys.getenv("APCA-PAPER-API-KEY-ID")`  &nbsp;
`'APCA-API-SECRET-KEY' = Sys.getenv("APCA-PAPER-API-SECRET-KEY")`

Notice how they are both named the same when being sent as headers in the API requests, but have "live" or "paper" inside the environment variable names to easily distinguish the two.

**Comment by fredwright68** [comment]
Thanks for getting back to me. Sorry to have been such a noob, but that was indeed the problem. I realized I had the LIVE key set wrong when I looked at the get_headers function. Thanks again and thanks for a great package. If I make money I’ll send you a bottle of champagne (or whatever you like). Cheers,
Fred

**Comment by jagg19** [comment]
@yogat3ch replace_order function added, as well as some new functions for the new features included in Alpaca's V2 update :)

@fredwright68 I'm not too sure if you made any permanent changes to get_headers or your environment variables, but I changed the naming conventions for. get_headers to make it clear between Live and Paper, so check the new updates for any changes. Thanks!

Going to close this issue now :)

**Comment by yogat3ch** [comment]
> @yogat3ch replace_order function added, as well as some new functions for the new features included in Alpaca's V2 update :)
> 
> @fredwright68 I'm not too sure if you made any permanent changes to get_headers or your environment variables, but I changed the naming conventions for. get_headers to make it clear between Live and Paper, so check the new updates for any changes. Thanks!
> 
> Going to close this issue now :)

Awesome!
