### ISSUE TITLE
Shorting stocks

### ISSUE THREAD

**Issue by jshousephd** [yogat3ch/AlpacaforR#9]
Hi there.
I'm just getting starting with Alpaca and buying stocks.  I like R and want to thank you for the effort that you've put into this AlpacaforR!

In addition to buying stocks to hold via AlpacaforR, I'm also interested in using it to short stocks.

Do you have the syntax for shorting a stock and then covering(closing) that position?
Kind regards

**Comment by yogat3ch** [comment]
Hi @jshousephd, 
I haven't heard from @jagg19 since August, but maybe this new thread will get his attention. I don't think the functionality for shorting has been built into the package yet. If you want to clone the repo, code this functionality, and submit a pull request that would be welcomed. 
I've actually been making quite a few updates over at the clone on yogat3ch/AlpacaforR, so if you don't get a response for a pull request here (if you write the code mentioned above) please feel free to send a pull request over there and I'll see about integrating it.

**Comment by jshousephd** [comment]
Hi @yogat3ch ,
Thanks for the response. This might be a bit beyond me at the moment. Since this functionality is already present in python scripting, I will probably just try to run that through R using reticulate or other python translator.

**Comment by jagg19** [comment]
Hi @jshousephd 

I really appreciate the kind words + feedback on AlpacaforR! 

I haven't built in the functionality for shorting like @yogat3ch  pointed out. I have been quite busy outside of AlpacaforR these last couple of months, so there is little V2 API functionality as well. I plan on making these updates in the coming weeks so users can use AlpacaforR under the V1 API as well as the new features V2 API. Shorting will be one of the first things I'll update, so I will keep this issue open until that's added

I haven't tried using python translators with this package so I'm not too sure how that would interact, but give it a shot on your paper account!

**Comment by jagg19** [comment]
Hi @jshousephd 

I just wanted to give a quick update on this issue. I finally added the V2 updates to this package, and its sitting in my V2-updates branch. I added a lot of new functionality and shorting is included in this update. I have not merged it yet because I still need to add some documentation and test it on my end a little more, but I am hoping to have this all completed by end of this week! Once again, I will wait until then to close this issue, but I just wanted to keep you in the loop.

**Comment by jshousephd** [comment]
Thanks @jagg19 for the update. I look forward to it!

**Comment by jagg19** [comment]
Hi @jshousephd 

I've went ahead and merged my V2 updates with my master branch, so you should be able to short stocks now! I will add that if you have one of the older accounts (check if your account starts with 3AP) then you need to create an entirely new account in order to use the new shorting features included in the V2 update. This is something on Alpaca's end, and not mine. 

Feel free to reach out or open new issues if you have any questions, or run into any issues on these updates but I've tested on my end and everything works well! I will go ahead and close this now, and I wish you the best of luck!

**Comment by jshousephd** [comment]
Thanks @jagg19 , I will take a look. I'm not sure if I have V2 or not. 
Thanks again for working on this.

**Comment by jagg19** [comment]
@jshousephd Depending on when you made your account, you may or may not have a newer account with the v2 API features incorporated on it. If you click "Account" on the left nav bar on your homepage dashboard (looks like a mini ID) you'll see your account number right on the top. If it starts with 3AP, then you'll need to create a new account. If it doesn't start with 3AP, then you should be good to go to use the new features, such as shorting!

I hope this helps, and I hope you make $$$ shorting on Alpaca!! Best of luck
